baseURL: "https://dev.www.hackingand.coffee"
theme: "github.com/Hacking-and-Coffee/hackingandcoffee-theme"
buildDrafts: false
buildFuture: false
buildExpired: false

# Production-specific configurations
